### ISSUE TITLE
TypeError when service prefix is not found

### ISSUE THREAD

**Issue by kmcquade** [salesforce/policy_sentry#239]
I think that a TypeError was killing my Cloudsplaining Lambda function which made me sad. 

```
Traceback (most recent call last):
  File "/usr/local/bin/policy_sentry", line 33, in <module>
    sys.exit(load_entry_point('policy-sentry==0.8.7', 'console_scripts', 'policy_sentry')())
  File "/usr/local/Cellar/policy_sentry/0.8.7/libexec/lib/python3.8/site-packages/policy_sentry/bin/cli.py", line 26, in main
    policy_sentry()
  File "/usr/local/Cellar/policy_sentry/0.8.7/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/policy_sentry/0.8.7/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/policy_sentry/0.8.7/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/policy_sentry/0.8.7/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/policy_sentry/0.8.7/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/policy_sentry/0.8.7/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/policy_sentry/0.8.7/libexec/lib/python3.8/site-packages/policy_sentry/command/query.py", line 84, in action_table
    query_action_table(name, service, access_level, condition, wildcard_only, fmt)
  File "/usr/local/Cellar/policy_sentry/0.8.7/libexec/lib/python3.8/site-packages/policy_sentry/command/query.py", line 163, in query_action_table
    output = get_actions_for_service(service)
  File "/usr/local/Cellar/policy_sentry/0.8.7/libexec/lib/python3.8/site-packages/policy_sentry/querying/actions.py", line 28, in get_actions_for_service
    for item in service_prefix_data["privileges"]:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by kmcquade** [comment]
This was fixed by #246 thanks to @reetasingh. Closing
