### ISSUE TITLE
Terraform module: Add support for Terraform 0.13+

### ISSUE THREAD

**Issue by kmcquade** [salesforce/policy_sentry#281]
FYI @dgubitosi - getting this error when using Terraform 0.13+.

Error message:

```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

Error: failed to execute "policy_sentry": Traceback (most recent call last):
  File "/usr/local/bin/policy_sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/policy_sentry/bin/cli.py", line 26, in main
    policy_sentry()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/policy_sentry/command/write_policy.py", line 95, in write_policy
    cfg = read_yaml_file(input_file)
  File "/usr/local/lib/python3.9/site-packages/policy_sentry/util/file.py", line 17, in read_yaml_file
    with open(filename, "r") as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'template.json'


  on ../ps-template/main.tf line 36, in data "external" "policy":
  36: data "external" "policy" {
```

### Steps to reproduce:

* Replace all instances of `"~> 0.12.8"` with `">= 0.12.8"`
* `tfenv install 0.13.5`
* `cd terraform_module/demo/`
* `terraform init` and `terraform plan`

**Comment by kmcquade** [comment]
Looks like this is because of the `external` data source.

Adding `depends_on` works. I will make a PR.

```hcl
data "external" "policy" {
  program = concat(local.command, ["--input-file", local_file.template.filename])
  depends_on = [local_file.template]
}
```

Note: HashiCorp specifically recommends NOT to use the `depends_on` for data sources, but I suspect that this might be a good use case, given that it works for 0.13.5 and for 0.12.8+.
