### ISSUE TITLE
description and role_arn keys don't seem to be supported in action mode input

### ISSUE THREAD

**Issue by robdew** [salesforce/policy_sentry#370]
the template YAML for Actions mode:

https://github.com/salesforce/policy_sentry/blob/master/examples/yml/actions.yml

creates a working template, but the extra keys of "description" and "role_arn" shown in the examples don't appear to be in the schema.

If you use:

```YAML
mode: actions
name: 'RoleNameWithActions'
description: 'Justification for privileges' # for auditability
role_arn: 'arn:aws:iam::123456789102:role/myRole' # for auditability
actions:
  - 'kms:CreateGrant'
 ```

You get:

```bash
$ policy_sentry write-policy --input-file actions.yml
Wrong keys 'description', 'role_arn' in {'mode': 'actions', 'name': 'RoleNameWithActions', 'description': 'Justification for privileges', 'role_arn': 'arn:aws:iam::123456789102:role/myRole', 'actions': ['kms:CreateGrant']}
Traceback (most recent call last):
  File "/usr/local/bin/policy_sentry", line 33, in <module>
    sys.exit(load_entry_point('policy-sentry==0.11.16', 'console_scripts', 'policy_sentry')())
  File "/usr/local/Cellar/policy_sentry/0.11.16/libexec/lib/python3.9/site-packages/policy_sentry/bin/cli.py", line 26, in main
    policy_sentry()
  File "/usr/local/Cellar/policy_sentry/0.11.16/libexec/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/policy_sentry/0.11.16/libexec/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/policy_sentry/0.11.16/libexec/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/policy_sentry/0.11.16/libexec/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/policy_sentry/0.11.16/libexec/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/Cellar/policy_sentry/0.11.16/libexec/lib/python3.9/site-packages/policy_sentry/command/write_policy.py", line 111, in write_policy
    policy = write_policy_with_template(cfg, min_length)
  File "/usr/local/Cellar/policy_sentry/0.11.16/libexec/lib/python3.9/site-packages/policy_sentry/command/write_policy.py", line 135, in write_policy_with_template
    policy = sid_group.process_template(cfg, minimize)
  File "/usr/local/Cellar/policy_sentry/0.11.16/libexec/lib/python3.9/site-packages/policy_sentry/writing/sid_group.py", line 490, in process_template
    check_actions_schema(cfg)
  File "/usr/local/Cellar/policy_sentry/0.11.16/libexec/lib/python3.9/site-packages/policy_sentry/writing/validate.py", line 70, in check_actions_schema
    raise Exception(
Exception: The provided template does not match the required schema for ACTIONS mode. Please use the create-template command to generate a valid YML template that Policy Sentry will accept.
```

policy_sentry, version 0.11.16

**Comment by kmcquade** [comment]
Those keys were removed at some point in a previous version, actually.

If you run `policy_sentry create-template -o test.yml -t action` you'll notice that `test.yml` includes the following data:

```yaml
mode: actions
name: ''
actions:
- ''
```

I realize this affects backwards compatibility so apologies on that one. But yeah those keys aren't valid or necessary anymore, so I will close this issue.
